/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#include <m8c.h>
// Poti address and mask defines
#pragma	ioport	Poti_Data_ADDR:	0x0
BYTE			Poti_Data_ADDR;
#pragma	ioport	Poti_DriveMode_0_ADDR:	0x100
BYTE			Poti_DriveMode_0_ADDR;
#pragma	ioport	Poti_DriveMode_1_ADDR:	0x101
BYTE			Poti_DriveMode_1_ADDR;
#pragma	ioport	Poti_DriveMode_2_ADDR:	0x3
BYTE			Poti_DriveMode_2_ADDR;
#pragma	ioport	Poti_GlobalSelect_ADDR:	0x2
BYTE			Poti_GlobalSelect_ADDR;
#pragma	ioport	Poti_IntCtrl_0_ADDR:	0x102
BYTE			Poti_IntCtrl_0_ADDR;
#pragma	ioport	Poti_IntCtrl_1_ADDR:	0x103
BYTE			Poti_IntCtrl_1_ADDR;
#pragma	ioport	Poti_IntEn_ADDR:	0x1
BYTE			Poti_IntEn_ADDR;
#define Poti_MASK 0x2
#pragma	ioport	Poti_MUXBusCtrl_ADDR:	0x1d8
BYTE			Poti_MUXBusCtrl_ADDR;
// Taster address and mask defines
#pragma	ioport	Taster_Data_ADDR:	0x4
BYTE			Taster_Data_ADDR;
#pragma	ioport	Taster_DriveMode_0_ADDR:	0x104
BYTE			Taster_DriveMode_0_ADDR;
#pragma	ioport	Taster_DriveMode_1_ADDR:	0x105
BYTE			Taster_DriveMode_1_ADDR;
#pragma	ioport	Taster_DriveMode_2_ADDR:	0x7
BYTE			Taster_DriveMode_2_ADDR;
#pragma	ioport	Taster_GlobalSelect_ADDR:	0x6
BYTE			Taster_GlobalSelect_ADDR;
#pragma	ioport	Taster_IntCtrl_0_ADDR:	0x106
BYTE			Taster_IntCtrl_0_ADDR;
#pragma	ioport	Taster_IntCtrl_1_ADDR:	0x107
BYTE			Taster_IntCtrl_1_ADDR;
#pragma	ioport	Taster_IntEn_ADDR:	0x5
BYTE			Taster_IntEn_ADDR;
#define Taster_MASK 0x10
#pragma	ioport	Taster_MUXBusCtrl_ADDR:	0x1d9
BYTE			Taster_MUXBusCtrl_ADDR;
// Taster Shadow defines
//   Taster_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define Taster_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
