//*****************************************************************************
//*****************************************************************************
//  FILENAME: I2CHW.h
//   Version: 1.90, Updated on 2011/6/28 at 6:9:30
//  Generated by PSoC Designer 5.1.2306
//
//  DESCRIPTION: UMName User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#ifndef I2CHW_SLAVE_INCLUDE
#define I2CHW_SLAVE_INCLUDE
#endif

#pragma fastcall16  I2CHW_Poll

//-------------------------------------------------
// Status variables for I2CHW API's.
//-------------------------------------------------

//
//export only the count values used in the i/o processing routine
//

#define I2CHW_READ_BUFTYPE                   0x0
#define I2CHW_READ_FLASH                     I2CHW_READ_BUFTYPE & 0x01

extern unsigned char     I2CHW_Write_Count;

#if (I2CHW_READ_BUFTYPE)
extern unsigned int    I2CHW_Read_CountHI;

#endif
extern unsigned char    I2CHW_Read_Count;

//-------------------------------------------------
// Constants for I2CHW API's.
//-------------------------------------------------
//
#define I2CHW_SLAVE_ADDR                    0x5

extern char I2CHW_bStatus;
extern char I2CHW_RsrcStatus;

//definition of  I2CHW_Poll() if User Module parameter is configured as "Polled" 
//otherwise function is stubbed out.

extern void I2CHW_Poll(void);
