//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED7SEG.h
//   Version: 1.20, Updated on 2011/12/1 at 17:22:54                                          
//  Generated by PSoC Designer 5.2.2401
//
//  DESCRIPTION: LED7SEG User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED7SEG_INCLUDE
#define LED7SEG_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED7SEG_Dim
#pragma fastcall16  LED7SEG_PutHex
#pragma fastcall16  LED7SEG_PutPattern
#pragma fastcall16  LED7SEG_DP 
#pragma fastcall16  LED7SEG_DispInt


//-------------------------------------------------
// Constants for LED7SEG API's.
//-------------------------------------------------
//
//
extern BYTE LED7SEG_DigitRAM[];
extern BYTE LED7SEG_ScanStatus;

//-------------------------------------------------
// Prototypes of the LED7SEG API.
//-------------------------------------------------
extern void  LED7SEG_Start(void);    
extern void  LED7SEG_Stop(void);    
extern void  LED7SEG_Dim(BYTE bDim);    
extern void  LED7SEG_Update(void);    
extern void  LED7SEG_PutHex(BYTE bValue, BYTE bDigit);                 
extern void  LED7SEG_PutPattern(BYTE bPattern, BYTE bDigit);                 
extern void  LED7SEG_DP(BYTE bOnOff, BYTE bDigit);                 
extern void  LED7SEG_DispInt(int iValue, BYTE bPos, BYTE bLen);                 

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------

#define LED7SEG_Digit1   0x01    
#define LED7SEG_Digit2   0x02    
#define LED7SEG_Digit3   0x04    
#define LED7SEG_Digit4   0x08    
#define LED7SEG_Digit5   0x10    
#define LED7SEG_Digit6   0x20    
#define LED7SEG_Digit7   0x40    
#define LED7SEG_Digit8   0x80    

#define LED7SEG_DimOn    0x01    
#define LED7SEG_DimOff   0x00    

#define LED7SEG_DpOn     0x01    
#define LED7SEG_DpOff    0x00    


#endif
