;;*****************************************************************************
;;*****************************************************************************
;;  ADC8INT.asm
;;  Version: 1.1, Updated on 2012/3/2 at 9:12:17
;;  Generated by PSoC Designer 5.2.2551
;;
;;  DESCRIPTION: ADC8 User Module ISR implementation file.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "ADC8.inc"

export _ADC8_ADC_ISR

export _ADC8_bResult
export  ADC8_bResult
export _ADC8_bfStatus
export  ADC8_bfStatus

AREA InterruptRAM(RAM)
  _ADC8_bResult:
   ADC8_bResult:       BLK   1  ;A/D value
  _ADC8_bfStatus:
   ADC8_bfStatus:      BLK   1  ;Data Valid Flag


AREA UserModules (ROM, REL)

_ADC8_ADC_ISR:
; ISR ,including jmptable takes 119 cpu cycles.)
   push A
   tst  reg[ADC8_ADC_CR],80h
   jz   .InRange

; Read Counter
.OverRange:
   mov  A,ffh
   jmp  .Done

.InRange:
   mov  A,reg[ADC8_CNT_DR0]
   mov  A,reg[ADC8_CNT_DR2]   ;A contains next prev value
   cpl  A

.Done:
   and  reg[ADC8_CNT_CR0], ~ADC8_ON 
   mov  reg[ADC8_CNT_DR1], 0xFF
   or   reg[ADC8_CNT_CR0], ADC8_ON

   mov  [ADC8_bfStatus],01h
   mov  [ADC8_bResult],A

   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom assembly code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   
   ;---------------------------------------------------
   ; Insert your custom assembly code above this banner
   ;---------------------------------------------------
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function below this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   
   ;PRESERVE_CPU_CONTEXT
   ;lcall _My_C_Function
   ;RESTORE_CPU_CONTEXT
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function above this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   pop A
   reti
