/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#include <m8c.h>
// Rx address and mask defines
#pragma	ioport	Rx_Data_ADDR:	0x0
BYTE			Rx_Data_ADDR;
#pragma	ioport	Rx_DriveMode_0_ADDR:	0x100
BYTE			Rx_DriveMode_0_ADDR;
#pragma	ioport	Rx_DriveMode_1_ADDR:	0x101
BYTE			Rx_DriveMode_1_ADDR;
#pragma	ioport	Rx_DriveMode_2_ADDR:	0x3
BYTE			Rx_DriveMode_2_ADDR;
#pragma	ioport	Rx_GlobalSelect_ADDR:	0x2
BYTE			Rx_GlobalSelect_ADDR;
#pragma	ioport	Rx_IntCtrl_0_ADDR:	0x102
BYTE			Rx_IntCtrl_0_ADDR;
#pragma	ioport	Rx_IntCtrl_1_ADDR:	0x103
BYTE			Rx_IntCtrl_1_ADDR;
#pragma	ioport	Rx_IntEn_ADDR:	0x1
BYTE			Rx_IntEn_ADDR;
#define Rx_MASK 0x4
// Tx address and mask defines
#pragma	ioport	Tx_Data_ADDR:	0x0
BYTE			Tx_Data_ADDR;
#pragma	ioport	Tx_DriveMode_0_ADDR:	0x100
BYTE			Tx_DriveMode_0_ADDR;
#pragma	ioport	Tx_DriveMode_1_ADDR:	0x101
BYTE			Tx_DriveMode_1_ADDR;
#pragma	ioport	Tx_DriveMode_2_ADDR:	0x3
BYTE			Tx_DriveMode_2_ADDR;
#pragma	ioport	Tx_GlobalSelect_ADDR:	0x2
BYTE			Tx_GlobalSelect_ADDR;
#pragma	ioport	Tx_IntCtrl_0_ADDR:	0x102
BYTE			Tx_IntCtrl_0_ADDR;
#pragma	ioport	Tx_IntCtrl_1_ADDR:	0x103
BYTE			Tx_IntCtrl_1_ADDR;
#pragma	ioport	Tx_IntEn_ADDR:	0x1
BYTE			Tx_IntEn_ADDR;
#define Tx_MASK 0x8
// ADC address and mask defines
#pragma	ioport	ADC_Data_ADDR:	0x0
BYTE			ADC_Data_ADDR;
#pragma	ioport	ADC_DriveMode_0_ADDR:	0x100
BYTE			ADC_DriveMode_0_ADDR;
#pragma	ioport	ADC_DriveMode_1_ADDR:	0x101
BYTE			ADC_DriveMode_1_ADDR;
#pragma	ioport	ADC_DriveMode_2_ADDR:	0x3
BYTE			ADC_DriveMode_2_ADDR;
#pragma	ioport	ADC_GlobalSelect_ADDR:	0x2
BYTE			ADC_GlobalSelect_ADDR;
#pragma	ioport	ADC_IntCtrl_0_ADDR:	0x102
BYTE			ADC_IntCtrl_0_ADDR;
#pragma	ioport	ADC_IntCtrl_1_ADDR:	0x103
BYTE			ADC_IntCtrl_1_ADDR;
#pragma	ioport	ADC_IntEn_ADDR:	0x1
BYTE			ADC_IntEn_ADDR;
#define ADC_MASK 0x20
// Relais address and mask defines
#pragma	ioport	Relais_Data_ADDR:	0x4
BYTE			Relais_Data_ADDR;
#pragma	ioport	Relais_DriveMode_0_ADDR:	0x104
BYTE			Relais_DriveMode_0_ADDR;
#pragma	ioport	Relais_DriveMode_1_ADDR:	0x105
BYTE			Relais_DriveMode_1_ADDR;
#pragma	ioport	Relais_DriveMode_2_ADDR:	0x7
BYTE			Relais_DriveMode_2_ADDR;
#pragma	ioport	Relais_GlobalSelect_ADDR:	0x6
BYTE			Relais_GlobalSelect_ADDR;
#pragma	ioport	Relais_IntCtrl_0_ADDR:	0x106
BYTE			Relais_IntCtrl_0_ADDR;
#pragma	ioport	Relais_IntCtrl_1_ADDR:	0x107
BYTE			Relais_IntCtrl_1_ADDR;
#pragma	ioport	Relais_IntEn_ADDR:	0x5
BYTE			Relais_IntEn_ADDR;
#define Relais_MASK 0x2
