/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADC8.h"
#include "E2PROM.h"
#include "Timer8.h"
#include "UART.h"

#endif
