/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#include <m8c.h>
// MCLK address and mask defines
#pragma	ioport	MCLK_Data_ADDR:	0x0
BYTE			MCLK_Data_ADDR;
#pragma	ioport	MCLK_DriveMode_0_ADDR:	0x100
BYTE			MCLK_DriveMode_0_ADDR;
#pragma	ioport	MCLK_DriveMode_1_ADDR:	0x101
BYTE			MCLK_DriveMode_1_ADDR;
#pragma	ioport	MCLK_DriveMode_2_ADDR:	0x3
BYTE			MCLK_DriveMode_2_ADDR;
#pragma	ioport	MCLK_GlobalSelect_ADDR:	0x2
BYTE			MCLK_GlobalSelect_ADDR;
#pragma	ioport	MCLK_IntCtrl_0_ADDR:	0x102
BYTE			MCLK_IntCtrl_0_ADDR;
#pragma	ioport	MCLK_IntCtrl_1_ADDR:	0x103
BYTE			MCLK_IntCtrl_1_ADDR;
#pragma	ioport	MCLK_IntEn_ADDR:	0x1
BYTE			MCLK_IntEn_ADDR;
#define MCLK_MASK 0x8
// I2CHWSDA address and mask defines
#pragma	ioport	I2CHWSDA_Data_ADDR:	0x4
BYTE			I2CHWSDA_Data_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSDA_IntEn_ADDR:	0x5
BYTE			I2CHWSDA_IntEn_ADDR;
#define I2CHWSDA_MASK 0x1
// I2CHWSCL address and mask defines
#pragma	ioport	I2CHWSCL_Data_ADDR:	0x4
BYTE			I2CHWSCL_Data_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSCL_IntEn_ADDR:	0x5
BYTE			I2CHWSCL_IntEn_ADDR;
#define I2CHWSCL_MASK 0x2
