/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "I2CHWMstr.h"
#include "I2CHWCommon.h"
#include "LCD.h"

#endif
