/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "I2CHWRSRCInits.h"
#include "I2CHWMMS.h"
#include "I2CHWMstr.h"
#include "PWM16.h"

#endif
