//*****************************************************************************
//*****************************************************************************
//  FILENAME: TX8SW.h
//  Version: 1.2, Updated on 2011/12/1 at 17:23:32
//  Generated by PSoC Designer 5.2.2401
//
//  DESCRIPTION: TX8 User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef TX8SW_INCLUDE
#define TX8SW_INCLUDE

#include <m8c.h>

// Create pragmas to support proper argument and return value passing 
#pragma fastcall16  TX8SW_Start
#pragma fastcall16  TX8SW_Stop
#pragma fastcall16  TX8SW_SendData
#pragma fastcall16  TX8SW_PutString
#pragma fastcall16  TX8SW_CPutString
#pragma fastcall16  TX8SW_PutChar
#pragma fastcall16  TX8SW_Write
#pragma fastcall16  TX8SW_CWrite
#pragma fastcall16  TX8SW_PutSHexByte
#pragma fastcall16  TX8SW_PutSHexInt
#pragma fastcall16  TX8SW_PutCRLF

//-------------------------------------------------
// Prototypes of the TX8SW API.
//-------------------------------------------------
// Low level TX functions
extern void  TX8SW_Start(void);
extern void  TX8SW_Stop(void);
extern void  TX8SW_SendData(BYTE bTxData);

// High level TX functions
extern void   TX8SW_PutString(BYTE * szRamString);
extern void   TX8SW_CPutString(const BYTE * szRomString);
extern void   TX8SW_PutChar(BYTE cData);
extern void   TX8SW_Write(BYTE * sRamData, BYTE bCount);
extern void   TX8SW_CWrite(const BYTE * sRomData, INT iCount);
extern void   TX8SW_PutSHexByte(BYTE bValue);
extern void   TX8SW_PutSHexInt(INT iValue);
extern void   TX8SW_PutCRLF(void);

#endif
// end of file TX8SW.h
