/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "EzADC.h"
#include "LCD.h"
#include "Timer32.h"

#endif
